### PR TITLE
first stab at putting protocol handlers in all processes

### PR DESCRIPTION
**Pull request by the8472**
it's not quite done, but i'd like some feedback. i had to untangle the gui and configuration concerns a bit to make it work in the child process.

### CODE REVIEW

**Comment by lidel** [comment]
Thank you. Went over it and I am okay with the direction of your changes. 
Use of `supressRecursion`  feels bit 'dirty', but I understand why it is there.

Some cosmetic things to keep in mind:

- Refactoring broke some UI tests (run via `jpm test`), which need to be fixed:
 -  [TypeError: button is undefined](https://travis-ci.org/lidel/ipfs-firefox-addon/jobs/96885703#L843)
 -  [TypeError: gw.enableHttpGatewayRedirect is not a function](https://travis-ci.org/lidel/ipfs-firefox-addon/jobs/96885703#L703)
- JSHint reported [some issues](https://travis-ci.org/lidel/ipfs-firefox-addon/jobs/96885703#L931): 
  - I don't have a strong opinion regarding singlequotes, feel free to disable it if you wish (or use singlequotes).
 - Add `"esnext": true,` in `jshint` section of `Gruntfile.js` to suppress errors about arrow function syntax (=>)  – use of ES6 is ok. 

Let me know when you feel it is ready ( if we merge this first, #29  will need to rebase :-) )

**Comment by the8472** [comment]
All tests pass now. The last jshint thing seems bogus to me since function definitions are hoisted while consts have a temporal dead zone.

**Comment by lidel** [comment]
I agree, in this particular case moving function does not improve readability.
To whitelist, just add this comment:

```javascript
function toggle(val) { /*jshint ignore:line*/
```

**Comment by the8472** [comment]
all green now

**Comment by lidel** [comment]
:+1:

**Comment by lidel** [comment]
FYI I submitted version 1.3.2 with these changes to Mozilla. 
It may take a few days to before it gets reviewed tho (Queue Position: 93 of 94).

**Comment by lidel** [comment]
@the8472 could you please take a look at #33  ?

**Pull request merged**
